### ISSUE TITLE
Error message when exporting to files

### ISSUE THREAD

**Issue by PromptJS19** [SynBioDex/SBOLCanvas#170]
I've finished my design and I was going to download it as a file then the software errored out like this

<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> java.util.ArrayList cannot be cast to java.util.Hashtable</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Hashtable utils.MxToSBOL.setupDocument(MxToSBOL.java:138) utils.MxToSBOL.toSBOL(MxToSBOL.java:84) servlets.Convert.doPost(Convert.java:58) javax.servlet.http.HttpServlet.service(HttpServlet.java:652) javax.servlet.http.HttpServlet.service(HttpServlet.java:733) org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) org.apache.catalina.filters.CorsFilter.handleSimpleCORS(CorsFilter.java:259) org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:163) </pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/9.0.45</h3></body></html>

can anyone help me? thanks!

**Comment by cjmyers** [comment]
Thanks for reporting this bug.  We have fixed this issue and include this fix in the latest version 1.2.1 that is now deployed at https://sbolcanvas.org.  Please let us know if you experience any other issues.

Fixed by PR #171

**Comment by PromptJS19** [comment]
<img width="1440" alt="Screen Shot 2564-06-07 at 17 52 06" src="https://user-images.githubusercontent.com/83409530/121004652-25ae7700-c7b9-11eb-931d-074507a0fbcd.png">

there's still an error

**Comment by cjmyers** [comment]
Sorry for your trouble.  Can you provide the steps that you take that lead to this error to help us reproduce it?

**Comment by cjmyers** [comment]
I've reproduced this error.  It seems to occur when you design something, upload it to SBH, download from SBH, edit it, and try to upload to SBH again (or export the file). @Randoom97 Any ideas on this one?  My guess is that there is some problem with the URI update when you take ownership and bring into sbolcanvas namespace.

**Comment by cjmyers** [comment]
It looks like the issue has to do with the fact that I had downloaded a design, edited it, but some components that I had built previously I did not edit.  However, I had removed them from SBH, so it made the links stale.  This is not really a valid workflow, since I should not have downloaded the design and then deleted the components from my private repo.  Not sure if this error would have appeared, if I had not done that.

**Comment by GC-repeat** [comment]
I'm getting the same error when designing something directly in SBOLCanvas using the "Import Component" feature and getting the component from the synbiohub server. It does it for all file formats. 

`Error
sbol-10604:Weak Validation Error: The URI contained by the definition property MUST refer to a ComponentDefinition object. Reference: SBOL Version 2.3.0 Section 7.7.1 on page 27 : https://sbolcanvas.org/id1`

**Comment by cjmyers** [comment]
Sorry this has slipped from our attention a bit.  Are you able to reproduce this in a specific small number of steps?  If so, can you step me through what you are trying to do.

**Comment by GC-repeat** [comment]
In my case if I add a sequence feature and try to export the file right away it works but after importing a component from the synbiohub.org server and the igem_collection for example I can't export the file anymore and get the `Error sbol-10604:Weak Validation Error...` error. Image export works in both cases.

**Comment by cjmyers** [comment]
We think we have fixed this issue.  Can you test it on our snapshot server:

https://canvas.sbolstandard.org

Thanks

**Comment by GC-repeat** [comment]
File export works with imported components on the snapshot server. 
Thanks

**Comment by geoffbaldwin** [comment]
See my 8th Nov issue. File>New Design leads to saving and upload error
Tested this on the linked snapshot server and the error is still there.
